namespace Agro_Express.Enum
{
    public enum State
    {
        __State__,
         Abia ,
         Adamawa,
         Akwa_Ibom,
         Anambra,
         Bauchi,
         Bayelsa,
         Benue,
         Borno,
         Cross_River,
         Delta,
         Ebonyi,
         Edo,
         Ekiti,
         Enugu,
         FCT,
         Gombe,
         Imo,
         Jigawa,
         Kaduna,
         Kano,
         Katsina,
         Kebbi,
         Kogi,
         Kwara,
         Lagos,
          Nassarawa,
          Niger,
          Ogun,
          Ondo,
          Osun,
           Oyo,
           Plateau,
            Rivers,
            Sokoto,
            Taraba,
            Yobe,
            Zamfara,

        
    }
}